// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmeneridwgiavindzoht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZW5lcmlkd2dpYXZpbmR6b2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDYzODUsImV4cCI6MjA3MTgyMjM4NX0.yK1-oF74e-_Uqi8RYBXnaMW20bYAdHrYGPkfHoBAYpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});